apiVersion: v1
kind: Service
metadata:
  name: agent-telemetry-grafana
  labels:
    app.kubernetes.io/name: agent-telemetry-grafana
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: agent-telemetry-grafana
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
