apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-telemetry-data
  labels:
    app.kubernetes.io/name: agent-telemetry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
