apiVersion: v1
kind: Service
metadata:
  name: agent-telemetry-server
  labels:
    app.kubernetes.io/name: agent-telemetry-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: agent-telemetry-server
  ports:
    - name: http
      port: 8443
      targetPort: http
      protocol: TCP
