apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-telemetry-grafana
spec:
  template:
    spec:
      containers:
        - name: grafana
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
