apiVersion: 1

datasources:
  - name: agent-telemetry
    uid: agent-telemetry
    type: frser-sqlite-datasource
    access: proxy
    isDefault: false
    jsonData:
      path: /var/lib/grafana/agent-telemetry.db
    editable: true
