// genhash reads schema.sql from the parent directory, computes its SHA256,
// and writes schema_hash.go alongside it. Invoked via go:generate.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
)

const outputTemplate = `// Code generated by genhash; DO NOT EDIT.

package schema

const Hash = %q
`

func main() {
	data, err := os.ReadFile("schema.sql")
	if err != nil {
		fmt.Fprintf(os.Stderr, "read schema.sql: %v\n", err)
		os.Exit(1)
	}
	sum := sha256.Sum256(data)
	hash := hex.EncodeToString(sum[:])
	out := fmt.Sprintf(outputTemplate, hash)
	if err := os.WriteFile("schema_hash.go", []byte(out), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write schema_hash.go: %v\n", err)
		os.Exit(1)
	}
}
